export const tableHeader = [
  'Day',
  'Date',
  'Check In',
  'Check Out',
  'Office Hours',
  'Working Hours',
  'Status',
];

export const tableBody = [
  {
    day: 'Thursday',
    date: '2023-05-11',
    checkIn: '10:00 AM',
    checkOut: '06:00 PM',
    officeHours: '8 Hours',
    workingHours: '8 Hours',
    status: 'Present',
  },
  {
    day: 'Thursday',
    date: '2023-05-11',
    checkIn: '10:00 AM',
    checkOut: '06:00 PM',
    officeHours: '8 Hours',
    workingHours: '8 Hours',
    status: 'Present',
  },
  {
    day: 'Thursday',
    date: '2023-05-11',
    checkIn: '10:00 AM',
    checkOut: '06:00 PM',
    officeHours: '8 Hours',
    workingHours: '8 Hours',
    status: 'Present',
  },
  {
    day: 'Thursday',
    date: '2023-05-11',
    checkIn: '10:00 AM',
    checkOut: '06:00 PM',
    officeHours: '8 Hours',
    workingHours: '8 Hours',
    status: 'Present',
  },
  {
    day: 'Thursday',
    date: '2023-05-11',
    checkIn: '10:00 AM',
    checkOut: '06:00 PM',
    officeHours: '8 Hours',
    workingHours: '8 Hours',
    status: 'Present',
  },
  {
    day: 'Thursday',
    date: '2023-05-11',
    checkIn: '10:00 AM',
    checkOut: '06:00 PM',
    officeHours: '8 Hours',
    workingHours: '8 Hours',
    status: 'Present',
  },
  {
    day: 'Thursday',
    date: '2023-05-11',
    checkIn: '10:00 AM',
    checkOut: '06:00 PM',
    officeHours: '8 Hours',
    workingHours: '8 Hours',
    status: 'Present',
  },
  {
    day: 'Thursday',
    date: '2023-05-11',
    checkIn: '10:00 AM',
    checkOut: '06:00 PM',
    officeHours: '8 Hours',
    workingHours: '8 Hours',
    status: 'Present',
  },
  {
    day: 'Thursday',
    date: '2023-05-11',
    checkIn: '10:00 AM',
    checkOut: '06:00 PM',
    officeHours: '8 Hours',
    workingHours: '8 Hours',
    status: 'Present',
  },
  {
    day: 'Thursday',
    date: '2023-05-11',
    checkIn: '10:00 AM',
    checkOut: '06:00 PM',
    officeHours: '8 Hours',
    workingHours: '8 Hours',
    status: 'Present',
  },
];
