// Style
import '@/styles/globals.css';

// Components
// import Navbar from '@/components/navbar/navbar';

// Provider
import SessionProvider from '@/components/provider';
import { Providers } from '@/providers';

// Meta Data
import type { Metadata } from 'next';

// Session
import { getServerSession } from 'next-auth';

// Fonts
import { Plus_Jakarta_Sans as PlusJakartaSans } from 'next/font/google';

const inter = PlusJakartaSans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Zenkoders HRMS',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <div className='p-5 flex flex-col h-screen gap-5'>
            <SessionProvider session={session}>
              {/* <Navbar /> */}
              <div className='h-full w-full'>{children}</div>
            </SessionProvider>
          </div>
        </Providers>
      </body>
    </html>
  );
}
