// Style
import '@/styles/globals.css';

// Components
// import Navbar from '@/components/navbar/navbar';

// Provider
import SessionProvider from '@/components/provider';
import { Providers } from '@/providers';

// Meta Data
import type { Metadata } from 'next';

// Session
import { getServerSession } from 'next-auth';

// Fonts
import { Plus_Jakarta_Sans as PlusJakartaSans } from 'next/font/google';

const inter = PlusJakartaSans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Zenkoders HRMS',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang='en'>
      <body className={(inter.className, 'bg-bg-gradient')}>
        <Providers>
          <div className='p-5 flex flex-col gap-5 relative overflow-hidden'>
            <SessionProvider session={session}>
              {/* <Navbar /> */}
              <div className='h-full w-full'>{children}</div>
              {/* <div className='absolute w-96 h-96 -z-50 bg-bg-gradient -top-20 -left-20 blur-xl rounded-full' />
              <div className='absolute w-96 h-96 -z-50 bg-bg-gradient bottom-0 right-0 blur-xl rounded-full' /> */}
            </SessionProvider>
          </div>
        </Providers>
      </body>
    </html>
  );
}
